name: Deploy Frontend

on:
  push:
    branches:
      - main  # Change this if needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

  deploy:
    needs: build-and-push  # Ensure deployment runs after building
    runs-on: ubuntu-latest

    steps:
    - name: SSH into EC2 and Deploy with Docker Compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/docker_compose
          git pull origin main  # If using a separate repo for compose
          docker pull garimajain2064/frontend:latest
          docker pull garimajain2064/backend:latest
          docker-compose down  # Stop existing containers
          docker-compose up -d  # Start fresh containers
